const LANGUAGES = [
    { short: 'af', international: 'Afrikaans', native: ''},
    { short: 'sq', international: 'Albanian', native: 'shqipe'},
    { short: 'ar', international: 'Arabic', native: '‎‫العربية‬‎'},
    { short: 'hy', international: 'Armenian', native: 'Հայերէն'},
    { short: 'az', international: 'Azerbaijani', native: 'azərbaycanca'},
    { short: 'eu', international: 'Basque', native: 'euskara'},
    { short: 'be', international: 'Belarusian', native: 'беларуская'},
    { short: 'bn', international: 'Bengali', native: 'বাংলা' },
    { short: 'bg', international: 'Bulgarian', native: 'български'},
    { short: 'ca', international: 'Catalan', native: 'català'},
    { short: 'zh-CN', international: 'Chinese (Simplified Han)', native: '中文（简体中文）'},
    { short: 'zh-TW', international: 'Chinese (Traditional Han)', native: '中文 (繁體中文)'},
    { short: 'hr', international: 'Croatian', native: 'hrvatski'},
    { short: 'cs', international: 'Czech', native: 'čeština'},
    { short: 'da', international: 'Danish', native: 'dansk'},
    { short: 'nl', international: 'Dutch', native: 'Nederlands'},
    { short: 'en', international: 'English', native: '' },
    { short: 'eo', international: 'Esperanto', native: 'esperanto'},
    { short: 'et', international: 'Estonian', native: 'eesti'},
    { short: 'tl', international: 'Filipino', native: '' },
    { short: 'fi', international: 'Finnish', native: 'suomi'},
    { short: 'fr', international: 'French', native: 'français'},
    { short: 'gl', international: 'Galician', native: 'galego'},
    { short: 'ka', international: 'Georgian', native: 'ქართული'},
    { short: 'de', international: 'German', native: 'Deutsch'},
    { short: 'el', international: 'Greek', native: 'Ελληνικά'},
    { short: 'gu', international: 'Gujarati', native: 'ગુજરાતી'},
    { short: 'ht', international: 'Haitian Creole', native: 'kreyòl ayisyen'},
    { short: 'iw', international: 'Hebrew', native: '‎‫עברית‬‎'},
    { short: 'hi', international: 'Hindi', native: 'हिन्दी'},
    { short: 'hu', international: 'Hungarian', native: 'magyar'},
    { short: 'is', international: 'Icelandic', native: 'íslenska'},
    { short: 'id', international: 'Indonesian', native: 'Bahasa Indonesia'},
    { short: 'ga', international: 'Irish', native: 'Gaeilge'},
    { short: 'it', international: 'Italian', native: 'italiano'},
    { short: 'ja', international: 'Japanese', native: '日本語'},
    { short: 'kn', international: 'Kannada', native: 'ಕನ್ನಡ'},
    { short: 'ko', international: 'Korean', native: '한국어'},
    { short: 'la', international: 'Latin', native: 'Lingua Latina'},
    { short: 'lv', international: 'Latvian', native: 'latviešu'},
    { short: 'lt', international: 'Lithuanian', native: 'lietuvių'},
    { short: 'mk', international: 'Macedonian', native: 'македонски'},
    { short: 'ms', international: 'Malay', native: 'Bahasa Melayu'},
    { short: 'mt', international: 'Maltese', native: 'Malti'},
    { short: 'no', international: 'Norwegian', native: 'norsk'},
    { short: 'fa', international: 'Persian', native: '‎‫فارسی‬‎'},
    { short: 'pl', international: 'Polish', native: 'polski'},
    { short: 'pt', international: 'Portuguese', native: 'português'},
    { short: 'ro', international: 'Romanian', native: 'română'},
    { short: 'ru', international: 'Russian', native: 'русский'},
    { short: 'sr', international: 'Serbian', native: 'Српски'},
    { short: 'sk', international: 'Slovak', native: 'slovenčina'},
    { short: 'sl', international: 'Slovenian', native: 'slovenščina'},
    { short: 'es', international: 'Spanish', native: 'español'},
    { short: 'sw', international: 'Swahili', native: 'Kiswahili'},
    { short: 'sv', international: 'Swedish', native: 'svenska'},
    { short: 'ta', international: 'Tamil', native: 'தமிழ்'},
    { short: 'te', international: 'Telugu', native: 'తెలుగు'},
    { short: 'th', international: 'Thai', native: 'ไทย'},
    { short: 'tr', international: 'Turkish', native: 'Türkçe'},
    { short: 'uk', international: 'Ukrainian', native: 'українська'},
    { short: 'ur', international: 'Urdu', native: '‎‫اردو‬‎'},
    { short: 'vi', international: 'Vietnamese', native: 'Tiếng Việt'},
    { short: 'cy', international: 'Welsh', native: 'Cymraeg'},
    { short: 'yi', international: 'Yiddish', native: 'יידיש'},
]